//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be://
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

public class EvenFibonacciNumbers {
    public static void main(String[] args){
        // declare variables
        int num1 = 1;
        int num2 = 2;
        int tempNum = 0;
        int value = num2; // initialize it to the first even number
        System.out.print(num1 + ", " + num2 + ", ");

        do{ // loops through fibonacci numbers
            tempNum = num1 + num2;
            if(tempNum < 4000000) { // if the tempNum is less than 4M, replace num1 with num2 & num2 with tempNum
                num1 = num2;
                num2 = tempNum;
                if (tempNum % 2 == 0)
                    value+= tempNum; // if tempNum is even, add it to the value
                System.out.print(num2 + ", ");
            }
      }while (tempNum < 4000000);
        System.out.println("\nThe value is " + value); // print the final value
    }
}

